add debugging config

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,6 +7,12 @@ on:
       - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
       - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
       - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
+  workflow_dispatch:
+    inputs:
+      debug:
+        description: "Run in debug mode"
+        required: false
+        default: "false"
 
 env:
   # ampere was taken :(
@@ -14,10 +20,12 @@ env:
   PACKAGE_FILENAME: "ampere_meter"
   OWNER: "jeffbrennan"
   REPO_NAME: "ampere"
+  NEW_VERSION: "0.1.4"
 
 jobs:
   details:
     runs-on: ubuntu-latest
+    if: github.event_name != 'workflow_dispatch' || inputs.debug != 'true'
     outputs:
       new_version: ${{ steps.release.outputs.new_version }}
       suffix: ${{ steps.release.outputs.suffix }}
@@ -46,6 +54,7 @@ jobs:
   check_pypi:
     needs: details
     runs-on: ubuntu-latest
+    if: github.event_name != 'workflow_dispatch' || inputs.debug != 'true'
     steps:
       - name: Fetch information from PyPI
         run: |
@@ -60,7 +69,7 @@ jobs:
 
       - name: Compare versions and exit if not newer
         run: |
-          NEW_VERSION=${{ needs.details.outputs.new_version }}
+          NEW_VERSION=${{ env.NEW_VERSION }}
           LATEST_VERSION=$latest_previous_version
           if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
             echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
@@ -72,6 +81,7 @@ jobs:
   setup_and_build:
     needs: [details, check_pypi]
     runs-on: ubuntu-latest
+    if: github.event_name != 'workflow_dispatch' || inputs.debug != 'true'
     steps:
       - uses: actions/checkout@v2
 
@@ -86,7 +96,7 @@ jobs:
       - name: Set project version
         # https://github.com/astral-sh/uv/issues/6298#issuecomment-2335034247
         run: |
-          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version  ${{ needs.details.outputs.new_version }}
+          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version  ${{ env.NEW_VERSION }}
 
       - name: Install dependencies
         run: uv sync
@@ -145,29 +155,38 @@ jobs:
           gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
 
   build_homebrew_bottles:
-    needs: [setup_and_build, details]
+    # needs: [setup_and_build, details]
     environment:
       name: release
     strategy:
       matrix:
-        os: [macos-latest, macos-14, ubuntu-latest]
+        # os: [macos-latest, macos-14, ubuntu-latest]
+        # os: [macos-latest]
+        os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
-      - name: Install Homebrew
-        run: |
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-
       - name: Checkout Homebrew Tap
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
         with:
           repository: ${{ env.OWNER }}/homebrew-${{ env.PACKAGE_NAME }}
-          token: ${{ secrets.BREW_TAP_TOKEN }}
+          # token: ${{ secrets.BREW_TAP_TOKEN }}
+
+      - name: Install Homebrew
+        run: |
+
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
+          echo "/opt/homebrew/bin" >> $GITHUB_PATH
+          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" || eval "$(/opt/homebrew/bin/brew shellenv)"
+          echo "HOMEBREW PATH: $(which brew)"
+          brew --version || echo "Failed to detect Homebrew version"
 
       - name: Install Dependencies
         run: brew install --build-bottle ./Formula/${{ env.PACKAGE_NAME }}.rb
 
       - name: Build Bottle
         run: |
+          brew tap ${{ env.OWNER }}/homebrew-${{ env.PACKAGE_NAME }}
           brew bottle ${{ env.PACKAGE_NAME }}
           mv ${{ env.PACKAGE_NAME }}--*.tar.gz ${{ env.PACKAGE_NAME }}-${{ runner.os }}.tar.gz
 
@@ -178,16 +197,17 @@ jobs:
           path: ${{ env.PACKAGE_NAME }}-*.tar.gz
 
   update_homebrew_tap:
-    needs: [build_homebrew_bottles, details]
+    # needs: [build_homebrew_bottles, details]
+    needs: [build_homebrew_bottles]
     environment:
       name: release
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Homebrew Tap
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
         with:
           repository: ${{ env.OWNER }}/homebrew-${{ env.PACKAGE_NAME }}
-          token: ${{ secrets.BREW_TAP_TOKEN }}
+          # token: ${{ secrets.BREW_TAP_TOKEN }}
 
       - name: Download Bottles
         uses: actions/download-artifact@v4
@@ -196,8 +216,8 @@ jobs:
 
       - name: Download new source tarball
         run: |
-          NEW_VERSION="${{ needs.details.outputs.new_version }}"
-          NEW_URL="https://github.com/${{ env.OWNER }}/${{ env.REPO_NAME}}/releases/download/${NEW_VERSION}/${{ env.PACKAGE_FILENAME }}-${NEW_VERSION}.tar.gz"
+          NEW_VERSION="${{ env.NEW_VERSION }}"
+          NEW_URL="https://github.com/${{ env.OWNER }}/${{ env.REPO_NAME }}/releases/download/${NEW_VERSION}/${{ env.PACKAGE_FILENAME }}-${NEW_VERSION}.tar.gz"
 
           echo "Fetching: $NEW_URL"
           curl -L -o source.tar.gz "$NEW_URL"
@@ -236,5 +256,5 @@ jobs:
           git config --global user.name "github-actions"
           git config --global user.email "github-actions@github.com"
           git add Formula/${{ env.PACKAGE_NAME }}.rb
-          git commit -m "Update ${{ env.PACKAGE_NAME }} to ${{ needs.details.outputs.new_version }}"
+          git commit -m "Update ${{ env.PACKAGE_NAME }} to ${{ env.NEW_VERSION }}"
           git push origin main
